### ISSUE TITLE
Unable to connect to ClamAV server

### ISSUE THREAD

**Issue by sanitghosh** [appwrite/php-clamav#33]
I am using a Linux server on IONOS. I followed the installation procedure through Composer and created a file to execute. But getting this error while trying to scan a file while uploading.

PHP Fatal error:  Uncaught RuntimeException: Unable to connect to ClamAV server in /var/www/vhosts/networksfortraining.org/sandbox-app-three.networksfortraining.org/wp-content/plugins/wp-s3-user-upload/vendor/appwrite/php-clamav/src/ClamAV/Network.php:66
Stack trace:
#0 /var/www/vhosts/networksfortraining.org/sandbox-app-three.networksfortraining.org/wp-content/plugins/wp-s3-user-upload/vendor/appwrite/php-clamav/src/ClamAV/ClamAV.php(36): Appwrite\ClamAV\Network->getSocket()
#1 /var/www/vhosts/networksfortraining.org/sandbox-app-three.networksfortraining.org/wp-content/plugins/wp-s3-user-upload/vendor/appwrite/php-clamav/src/ClamAV/ClamAV.php(52): Appwrite\ClamAV\ClamAV->sendCommand()
#2 /var/www/vhosts/networksfortraining.org/sandbox-app-three.networksfortraining.org/wp-content/plugins/wp-s3-user-upload/inc/ucua-functions.php(371): Appwrite\ClamAV\ClamAV->ping()
#3 /var/www/vhosts/networksfortraining.org/sandbox-app-three.networksfortraining.org/wp-includes/class-wp-hook.php(324): aws_s3_upload_process()
#4 /var/www/vhosts/networksfortraining.org/sandbox-app-three.networksfortraining.org/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#5 /var/www/vhosts/networksfortraining.org/sandbox-app-three.networksfortraining.org/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /var/www/vhosts/networksfortraining.org/sandbox-app-three.networksfortraining.org/wp-admin/admin-ajax.php(192): do_action()
#7 {main}
  thrown in /var/www/vhosts/networksfortraining.org/sandbox-app-three.networksfortraining.org/wp-content/plugins/wp-s3-user-upload/vendor/appwrite/php-clamav/src/ClamAV/Network.php on line 66

**Comment by moshOntong-IT** [comment]
The issue might be related on this 
![image](https://github.com/user-attachments/assets/cad6c647-b1a1-4d45-8c84-ec475f75a92e)


You can found this when you are try to log the appwrite/clamav container

**Comment by teian** [comment]
This looks like it's not a bug in the package rather your server cannot download the daily.cvd database
